/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FootballRouteImport } from './routes/football'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCompetitionsRouteImport } from './routes/_authenticated/admin/competitions'
import { Route as AuthenticatedAdminExposureRouteImport } from './routes/_authenticated/admin/exposure'
import { Route as AuthenticatedAdminMappingsRouteImport } from './routes/_authenticated/admin/mappings'
import { Route as AuthenticatedAdminMatchesRouteImport } from './routes/_authenticated/admin/matches'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedMyBetsIndexRouteImport } from './routes/_authenticated/my-bets/index'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedAdminFinanceIndexRouteImport } from './routes/_authenticated/admin/finance/index'
import { Route as AuthenticatedAdminIntegrationsIndexRouteImport } from './routes/_authenticated/admin/integrations/index'
import { Route as AuthenticatedAdminLogsIndexRouteImport } from './routes/_authenticated/admin/logs/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballRoute = FootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCompetitionsRoute =
  AuthenticatedAdminCompetitionsRouteImport.update({
    id: '/competitions',
    path: '/competitions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExposureRoute =
  AuthenticatedAdminExposureRouteImport.update({
    id: '/exposure',
    path: '/exposure',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMappingsRoute =
  AuthenticatedAdminMappingsRouteImport.update({
    id: '/mappings',
    path: '/mappings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMatchesRoute =
  AuthenticatedAdminMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedMyBetsIndexRoute =
  AuthenticatedMyBetsIndexRouteImport.update({
    id: '/my-bets/',
    path: '/my-bets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFinanceIndexRoute =
  AuthenticatedAdminFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationsIndexRoute =
  AuthenticatedAdminIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsIndexRoute =
  AuthenticatedAdminLogsIndexRouteImport.update({
    id: '/logs/',
    path: '/logs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/football': typeof FootballRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/competitions': typeof AuthenticatedAdminCompetitionsRoute
  '/admin/exposure': typeof AuthenticatedAdminExposureRoute
  '/admin/mappings': typeof AuthenticatedAdminMappingsRoute
  '/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/my-bets/': typeof AuthenticatedMyBetsIndexRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
  '/admin/finance/': typeof AuthenticatedAdminFinanceIndexRoute
  '/admin/integrations/': typeof AuthenticatedAdminIntegrationsIndexRoute
  '/admin/logs/': typeof AuthenticatedAdminLogsIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/football': typeof FootballRoute
  '/admin/competitions': typeof AuthenticatedAdminCompetitionsRoute
  '/admin/exposure': typeof AuthenticatedAdminExposureRoute
  '/admin/mappings': typeof AuthenticatedAdminMappingsRoute
  '/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/my-bets': typeof AuthenticatedMyBetsIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceIndexRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsIndexRoute
  '/admin/logs': typeof AuthenticatedAdminLogsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/football': typeof FootballRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/competitions': typeof AuthenticatedAdminCompetitionsRoute
  '/_authenticated/admin/exposure': typeof AuthenticatedAdminExposureRoute
  '/_authenticated/admin/mappings': typeof AuthenticatedAdminMappingsRoute
  '/_authenticated/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/my-bets/': typeof AuthenticatedMyBetsIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
  '/_authenticated/admin/finance/': typeof AuthenticatedAdminFinanceIndexRoute
  '/_authenticated/admin/integrations/': typeof AuthenticatedAdminIntegrationsIndexRoute
  '/_authenticated/admin/logs/': typeof AuthenticatedAdminLogsIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/football'
    | '/admin'
    | '/admin/competitions'
    | '/admin/exposure'
    | '/admin/mappings'
    | '/admin/matches'
    | '/admin/tickets'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/my-bets/'
    | '/wallet/'
    | '/admin/finance/'
    | '/admin/integrations/'
    | '/admin/logs/'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/football'
    | '/admin/competitions'
    | '/admin/exposure'
    | '/admin/mappings'
    | '/admin/matches'
    | '/admin/tickets'
    | '/admin/users'
    | '/account'
    | '/admin'
    | '/my-bets'
    | '/wallet'
    | '/admin/finance'
    | '/admin/integrations'
    | '/admin/logs'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/football'
    | '/_authenticated/admin'
    | '/_authenticated/admin/competitions'
    | '/_authenticated/admin/exposure'
    | '/_authenticated/admin/mappings'
    | '/_authenticated/admin/matches'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/my-bets/'
    | '/_authenticated/wallet/'
    | '/_authenticated/admin/finance/'
    | '/_authenticated/admin/integrations/'
    | '/_authenticated/admin/logs/'
    | '/_authenticated/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FootballRoute: typeof FootballRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football': {
      id: '/football'
      path: '/football'
      fullPath: '/football'
      preLoaderRoute: typeof FootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/competitions': {
      id: '/_authenticated/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AuthenticatedAdminCompetitionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exposure': {
      id: '/_authenticated/admin/exposure'
      path: '/exposure'
      fullPath: '/admin/exposure'
      preLoaderRoute: typeof AuthenticatedAdminExposureRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mappings': {
      id: '/_authenticated/admin/mappings'
      path: '/mappings'
      fullPath: '/admin/mappings'
      preLoaderRoute: typeof AuthenticatedAdminMappingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/matches': {
      id: '/_authenticated/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AuthenticatedAdminMatchesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/my-bets/': {
      id: '/_authenticated/my-bets/'
      path: '/my-bets'
      fullPath: '/my-bets/'
      preLoaderRoute: typeof AuthenticatedMyBetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/finance/': {
      id: '/_authenticated/admin/finance/'
      path: '/finance'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AuthenticatedAdminFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/integrations/': {
      id: '/_authenticated/admin/integrations/'
      path: '/integrations'
      fullPath: '/admin/integrations/'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs/': {
      id: '/_authenticated/admin/logs/'
      path: '/logs'
      fullPath: '/admin/logs/'
      preLoaderRoute: typeof AuthenticatedAdminLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCompetitionsRoute: typeof AuthenticatedAdminCompetitionsRoute
  AuthenticatedAdminExposureRoute: typeof AuthenticatedAdminExposureRoute
  AuthenticatedAdminMappingsRoute: typeof AuthenticatedAdminMappingsRoute
  AuthenticatedAdminMatchesRoute: typeof AuthenticatedAdminMatchesRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminFinanceIndexRoute: typeof AuthenticatedAdminFinanceIndexRoute
  AuthenticatedAdminIntegrationsIndexRoute: typeof AuthenticatedAdminIntegrationsIndexRoute
  AuthenticatedAdminLogsIndexRoute: typeof AuthenticatedAdminLogsIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCompetitionsRoute: AuthenticatedAdminCompetitionsRoute,
    AuthenticatedAdminExposureRoute: AuthenticatedAdminExposureRoute,
    AuthenticatedAdminMappingsRoute: AuthenticatedAdminMappingsRoute,
    AuthenticatedAdminMatchesRoute: AuthenticatedAdminMatchesRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminFinanceIndexRoute: AuthenticatedAdminFinanceIndexRoute,
    AuthenticatedAdminIntegrationsIndexRoute:
      AuthenticatedAdminIntegrationsIndexRoute,
    AuthenticatedAdminLogsIndexRoute: AuthenticatedAdminLogsIndexRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedMyBetsIndexRoute: typeof AuthenticatedMyBetsIndexRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedMyBetsIndexRoute: AuthenticatedMyBetsIndexRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FootballRoute: FootballRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
